import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import RegistrationController from "../../../src/Web/Http/RegistrationController"
import { useEffect, useState } from 'react'

function generateQuickGuid() {
  return Math.random().toString(36).substring(2, 15) +
      Math.random().toString(36).substring(2, 15);
}

export default function Home() {
  const [name, setName] = useState("Rahmat Agung Julians")
  const [age, setAge] = useState(20)
  const [registration, setRegistration] = useState([])

  const addRegistration = () => {
    let registrator = new RegistrationController().register(
      {name: name, age: age}
    )

    setRegistration(registrator)
    setAge(age + 1)
    setName(generateQuickGuid)
  }

  useEffect(() => {
    addRegistration()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => addRegistration()} className={styles.button}>Add more registration</button>
        <div className={styles.grid}>
          {
            registration?.length > 0 && (
              registration.map((item, index) => {
                return (
                  <div key={index} className={styles.card}>
                    <h3>{item.name}</h3>
                    <p>{item.age}</p>
                  </div>
                )
              })
            )
          }
        </div>
      </main>
    </div>
  )
}
